name: Build File

on: [push]

jobs:
  token-job:
    runs-on: macos-latest # Change this to macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode_16.0.app/Contents/Developer

      - name: Set ACCESS_TOKEN environment variable
        run: echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> $GITHUB_ENV
        
      - name: Change to Project Directory
        run: cd GitHubRepo # Set the working directory to the GitHubRepo folder

      - name: Build Xcode Project
        run: |
          cd GitHubRepo   # Ensure we're in the right directory
          xcodebuild -scheme GitHubRepo -configuration Release
